from dev_tools.utils import LuaLoader
from module.base.utils import location2node
from module.logger import logger  # Change folder automatically
from module.os.map_data import DIC_OS_MAP


class OSChapter:
    def __init__(self):
        self.chapter = {}
        data = LOADER.load('sharecfg/world_chapter_random.lua')
        names = self.extract_chapter_name()
        shapes = self.extract_map_size()
        for index, chapter in data.items():
            if not isinstance(index, int) or index >= 200:
                continue
            old = DIC_OS_MAP.get(index, {})
            self.chapter[index] = {
                'shape': shapes.get(index, old.get('shape')),
                'hazard_level': chapter['hazard_level'],
                'name': names.get(index, chapter['name']),
            }
        for index, data in self.extract_map_position().items():
            self.chapter[index].update(data)

    def extract_chapter_name(self):
        LOADER.server = 'en-US'
        data = LOADER.load('sharecfg/world_chapter_random.lua')
        out = {}
        for index, chapter in data.items():
            if not isinstance(index, int) or index >= 200:
                continue
            out[index] = chapter['name'].replace('é', 'e')
        if 40000 in data:
            out[154] = data[40000]['name']
        return out

    def extract_map_size(self):
        LOADER.server = 'en-US'
        data = LOADER.load('sharecfgdata/world_chapter_template.lua')
        out = {}
        for full_index, chapter in data.items():
            if not full_index // 1000000 == 1 or not chapter['map_sight']:
                continue
            index = (full_index % 1000000) // 1000
            if index < 10:
                index -= 1
            out[index] = location2node(self.parse_map_data(chapter['grids']))
        return out

    @staticmethod
    def parse_map_data(grids):
        y = [grid[0] for grid in grids.values()]
        x = [grid[1] for grid in grids.values()]
        return max(x) - min(x), max(y) - min(y)

    def extract_map_position(self):
        LOADER.server = 'en-US'
        data = LOADER.load('sharecfg/world_chapter_colormask.lua')
        out = {}
        for chapter in data.values():
            if 'serial_number' not in chapter:
                continue
            index = int(chapter['serial_number'])
            if index < 10:
                index -= 1
            area = chapter['area_pos']
            offset = chapter['offset_pos']
            out[index] = {
                'area_pos': (area[0], area[1]),
                'offset_pos': (offset[0], offset[1]),
                'region': chapter['regions'],
            }
        return out

    def encode(self):
        lines = [
            '# This file was automatically generated by dev_tools/os_extract.py.',
            "# Don't modify it manually.",
            '',
            'DIC_OS_MAP = {',
        ]
        for index, chapter in self.chapter.items():
            lines.append(f'    {index}: {chapter!r},')
        lines.append('}')
        return lines

    def write(self, file):
        print(f'writing {file}')
        with open(file, 'w', encoding='utf-8') as f:
            for text in self.encode():
                f.write(text + '\n')


FOLDER = ''
SAVE = 'module/os/map_data.py'
LOADER = LuaLoader(FOLDER, server='en-US')
OSChapter().write(SAVE)
